### ISSUE TITLE
feature request: embedded huey: programatically add data

### ISSUE THREAD

**Issue by declann** [rpbouman/huey#143]
Hi,

Below I link to a notebook where I embed huey in an iframe and it works excellently, but, I can only manually add data.

It includes a challenge feature request to programatically add data.

I understand from discussion @rpbouman currently it's not possible to initialize any data. Fixing this would permit initializing data **and** reports (already possible through url hash).

Notebook: https://observablehq.com/@declann/embedded-huey-data-load

Thanks
Declan

**Comment by rpbouman** [comment]
I will do some experiments on this either friday or the weekend. Should be done quickly.

If possible I will use postMessage;

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by declann** [comment]
Awesome idea. If postMessage works then I think that postMessage of apache arrow tables might be interesting?

Could involve a little bit of hacking depending on progress here:

https://github.com/apache/arrow/issues/39017

**Comment by rpbouman** [comment]
Hi @declann!

Well, it absolutely works, in principle. I just created a small test file that embeds huey in an iframe, like you suggested, with an interface that lets you send requests to it:

```
<!doctype html>
<html>
  <head>
    <style>
      textarea {
        display: block;
      }
    </style>
  </head>
  <body>
    <iframe id="frame" height="600" width="800" src="C:\roland\projects\huey\src\index.html"></iframe>
    <br/>
    <label for="requestId">Request Id:</label><select id="requestId">
      <option></option>
      <option>loadFile</option>
      <option>runQuery</option>
    </select>
    <br/>
    <label for="requestData">Request Data:</label>
    <textarea id="requestData">
    </textarea>
    <button id="sendMessage">Send Message...</button>
    <script>
      document.getElementById('sendMessage').addEventListener('click', function(event){
        var requestId = document.getElementById('requestId').value;
        if (requestId.value ===''){
          return;
        }
        var postData = document.getElementById('requestData').value;
        var message = {
          requestId: requestId,
          postData: postData
        };
        
        var frame = document.getElementById('frame');
        frame.contentWindow.postMessage(message, '*');
      });
    </script>
    
  </body>
</html>
```

Inside huey (App/App.js: initApplication) I added an eventlistener to the window that receives posted messages as events:

```
  window.addEventListener('message', function(event){
    var eventData = event.data;
    switch (eventData.requestId){
      default:
        showErrorDialog({
          title: 'Error handling posted message',
          description: `The request ${eventData.requestId} was not recognizeded as a valid requestId.` 
        });
    }
  });
```

To take this forward, I would propose to build a new Class (sinlgleton) in huey ("MessageProcessor" oslt) that attaches itself to the window and then takes care of all the message processing.

As to what kind of messages would make sense:
- sendFile: this would basically let you send a message with a blob, along with some metadata (mime type, file name etc) which huey could then register as file with ducbdb/wasm's registerFileBuffer (https://shell.duckdb.org/docs/classes/index.AsyncDuckDB.html#registerFileBuffer)
- execute query: this would let you send a query (probably allow for several formats, like url hash, js object)

I suppose to really make it usable it should also be possible to control what ui elements should be rendered, this is something that huey should then be able to pick up from some configuration data it reads from the frame element, or maybe there is a better way to do that.

Alternatively, it could also be that there could be a better way than embedding an entire page with the iframe.
It would absolutely require refactoring as the huey code is now pretty narrow minded and focused on itself, not so much for reusable components. But that could change of course. 

Perhaps you can make a few mockups to convey how you plan to use it, and then I'm sure we can work something out.

CHeers,
Roland.

**Comment by declann** [comment]
Cool stuff!

Working in iframe here, change the select box triggers an alert: https://observablehq.com/d/d2ad9b5b3f9bcdd9

I think a component would be a nice goal, ultimately - so huey could be embedded inside notebooks and webpages and web apps. [graphic walker](https://github.com/Kanaries/graphic-walker) is a visualization tool that can be embedded in this way. It has nice flexibility with UI and a pivot table output also, but it doesn't have duckdb.

I think that only an iframe and communicating files will permit a lot of experimentation. It's effectively like a component (functionally speaking not sure about the difference? Component might have a nicer api?).
It's possible to setup many in a single notebook and control their data. I think it's possible to refresh locally updated Parquet files, something I can try with [Framework](https://observablehq.com/framework/).

I can't make a clear endgame mockup of my usecases now: I'm also experimenting with Mosaic and dashboard type outputs - but highly bespoke things. For general purpose investigating or reporting model output (on mad volumes) - that's the gap where I'm exploring Huey right now.

**Comment by rpbouman** [comment]
Thanks Declann, that is very helpful!

**Comment by declann** [comment]
I modified your event listener to do `uploadUi.uploadFiles([eventData.url])` and send in a url with the postMessage to be able to programmatically upload data:

[Screencast from 2024-10-05 16-05-51.webm](https://github.com/user-attachments/assets/fa43b3a9-87bc-45a8-9e79-46bf7e6c5669)

What I really want to upload is in Arrow format: a useful format for postMessage and a useful format for embedding usecases, and DuckDB [supports](https://duckdb.org/docs/api/wasm/data_ingestion.html#apache-arrow) loading Arrow. [AFAIK](https://stackoverflow.com/questions/36319620/how-to-pass-a-file-object-via-postmessage-or-any-similar-function) File objects can't be passed over postMessage

**Comment by rpbouman** [comment]
Hi Declan!

> send in a url with the postMessage

Ok! Thanks for trying that. But I think it would be easier to just set the hash if you have an url, as that would automatically load

> File objects can't be passed over postMessage

Thanks for trying that! Good to know and really a pity.
Can you pass a buffer or Blob through postmessage? 
Because the WASM API has a method to register a buffer as if its a file (https://shell.duckdb.org/docs/classes/index.AsyncDuckDB.html#registerFileBuffer). 

With that one could send something like:

const file = ...;
const reader = new FileReader();
reader.addEventListener('loadend', function(evt){
  const buffer = reader.result;
  const array = new Uint8Array(buffer);
  frame.postMessage({id: 'loadBuffer', name: file.name, data: array})
});
reader.readAsArrayBuffer(file);

> What I really want to upload is in Arrow format: 

Ok, but what would be the method in DuckDB WASM to expose that data so you can write SQL against it?

**Comment by declann** [comment]
It seems to me like that would work! I'll try it when I get back to this,
with the goal of skelloting a vscode extension 😀

**Comment by rpbouman** [comment]
@declann ". [AFAIK](https://stackoverflow.com/questions/36319620/how-to-pass-a-file-object-via-postmessage-or-any-similar-function) File objects can't be passed over postMessage" 

I just did an experiment, and it seems to work okay for me. I will try and prepare a branch with this stuff so you can give it a whirl ok? Probably wednesday.

**Comment by declann** [comment]
Well interesting, if that works, cool! I'll be happy to check it out, thanks!

**Comment by rpbouman** [comment]
Hi Declann, 

please take a look at branch https://github.com/rpbouman/huey/tree/issue-143-postMessageInterface

If you pull that one you'll have a new dir in src, PostMessageInterface.
That dir has a PostMessageTestbed.html file which you can start instead of the huey index.html

The general flow is like this:

- the hosting page should setup a frame or iframe where it will host huey in. (example: https://github.com/rpbouman/huey/blob/issue-143-postMessageInterface/src/PostMessageInterface/PostMessageTestbed.html#L37)
- the hosting page should set up a 'message' event handler, which huey will call out to to communicate the effect of any requests you send to it. (Example: https://github.com/rpbouman/huey/blob/issue-143-postMessageInterface/src/PostMessageInterface/PostMessageTestbed.html#L70)
- After setting up the event handler, the hosting page can set the src of the frame in order to load huey (example: https://github.com/rpbouman/huey/blob/issue-143-postMessageInterface/src/PostMessageInterface/PostMessageTestbed.html#L103) 

Huey will load in the frame and when it's done loading, it detects whether it is hosted from a frame, and if so it will post a message to the parent window (i.e. the hosting window) to indicate that it is ready for receiving requests from the hosting page (example: https://github.com/rpbouman/huey/blob/issue-143-postMessageInterface/src/PostMessageInterface/PostMessageTestbed.html#L74). In the example, this is the trigger for the hosting page to reveal a (minimal) UI to allow the user to send messages to the framed huey app.

To send messages to the framed huey app, call the postMessage method of the window object associated with the frame where huey is hosted. This standard method (https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) should receive to arguments, the message and some options. (Example: https://github.com/rpbouman/huey/blob/issue-143-postMessageInterface/src/PostMessageInterface/PostMessageTestbed.html#L54)

The types of messages and possible responses are defined in the PostMessageProtocol class. The page hosting huey should probably include that so it can refer to the various constants inside it. (example: https://github.com/rpbouman/huey/blob/issue-143-postMessageInterface/src/PostMessageInterface/PostMessageTestbed.html#L39)

The messages you send have this general structure:
```
{
  requestId: <some id>,
  requestType: <some request type>,
  body {
    <request type specific options >
  }
}
```  

- The `requestId` is for the calling application and serves as a correlation id: the response you receive contains a reference to the same id so the calling app can figure out what response belongs to what request.
- The `requestType` indicates what command your sending to huey. This should be a REQUEST_% constant form the PostMessageControl class. Currently we only have two request types, REQUEST_PING and REQUEST_CREATE_DATASOURCE
- the body contains any options and settings (data) that are required for the correct execution of the request. Its contents will depend on what kind of request is to be executed.

After huey executes the command, it will send a response, also using the postMessage method. That's why the hosting app should listen to responses send by huey, so that it knows the command was executed. The responses look like this:

```
{
  messageType: 'response', //PostMessageProtocol.RESPONSE
  status: {
    code: ...one of the PostMessageProtocol.STATUS_% codes, 
    message: ...some text that briefly outlines the status of executing the request...,
    sent: ...timestamp when the response was sent back to the hosting window...
  },
  request: {
    messageType: ...the request type sent by the hosting app,
    requestId: the id sent by the hosting app
    received: ...timestamp when the request was received by huey...
  },
  body: {
    ...response specific data, typically varies with the request that elicited the response...
  }
}
```

For the create datasource request, the body is basically the datasource config data that one would also send to the DuckDbDataSource constructor (https://github.com/rpbouman/huey/blob/issue-143-postMessageInterface/src/DataSource/duckdb/DuckDbDataSource.js)

**Comment by rpbouman** [comment]
Probably need to align the names messageType/requestType.

**Comment by rpbouman** [comment]
Hi Declan, did you get a chance to try it out? Pls let me know what you think.

**Comment by declann** [comment]
Hi Roland! Sorry I didn't get to do this yet. I have some time today (after today then late this week also).
Seems I can't see the branch - is it offline?

https://github.com/rpbouman/huey/tree/issue-143-postMessageInterface gives me a 404

Cheers!
Declan

**Comment by declann** [comment]
Hi Roland, I think you quite nailed this protocol setup, and I like the new Clone button implementation (and I'm happy I am learning old new things about the web here!!)

But I wonder if File and the available DuckDbDataSources allow me to set data that's generated programatically. I think a File must come from the filesystem from a user exactly as in the testbed, which leaves the DuckDbDataSources, and I think all of the existing ones require Files, with no way I am aware of to register files externally?

So perhaps we need a new datasource for Arrow data that uses [`insertArrowTable`](https://duckdb.org/docs/api/wasm/data_ingestion#apache-arrow) and accepts the data to be loaded in Arrow format, and for these calls to be accessible from the protocol. I used insertArrowTable just today in a separate project - it's efficient and compact (the linked doc includes and End of Stream code, I found I didn't even need this)

Alternatively, maybe a `registerFileText` call over the protocol would be workable, before sending CSV/JSON file matching the registered file name.

But Arrow is especially efficient at this boundary; duckdb uses it internally, and there are good Javascript libraries to generate Arrow tables on the external side (`apache-arrow` and [flechette](https://github.com/uwdata/flechette)).

What do you think about adding Arrow functionality here?

If I missed a possibility that I can test now (for data generated externally by JS using any format), please let me know!

**Comment by declann** [comment]
Thanks a lot Roland!

Another thing I'm just after considering is if the parent can create a blob URL and send to the client. Just messing in devtools with a fetch, it seems like this can work. But I can't simply put URL into the iframe URL upload function: I guess because blobs have no file extension or the urls otherwise aren't recognised by huey or duckdb.

That could be a relatively easy fix but I'm still interested in Arrow. For, for instance a vscode extension which would be a nice step imo, perhaps either approach will do however.

![image](https://github.com/user-attachments/assets/54fcc9f3-028c-4a1a-8ecd-78ef979efd88)

**Comment by declann** [comment]
Just to note about Arrow, `insertArrowTable` will create a table by default, but you can call it again with `create: false` which will append to an existing table. If you expose this functionality, then for example:

Then the parent can create a `version` column starting at 0 or 1, and on each update append increasing versions, and the different versions will be navigable (comparable) inside huey.

**Comment by rpbouman** [comment]
> Another thing I'm just after considering is if the parent can create a blob URL and send to the client. 

What did the actual postmessage look like?
Can you load such urls using the DuckDB command line directly? (If not, then that's the issue)

**Comment by rpbouman** [comment]
> Just to note about Arrow, `insertArrowTable` will create a table by default, but you can call it again with `create: false` which will append to an existing table. If you expose this functionality, then for example:
> Then the parent can create a `version` column starting at 0 or 1, and on each update append increasing versions, and the different versions will be navigable (comparable) inside huey. I like this way to compare reports, rather than deleting data or maintaining it in a separate tab

Ok but that really sounds like a pretty specific use case, I'm not sure I should focus on that right now.

**Comment by rpbouman** [comment]
> But Arrow is especially efficient at this boundary; duckdb uses it internally, and there are good Javascript libraries to generate Arrow tables on the external side (`apache-arrow` and [flechette](https://github.com/uwdata/flechette)).
> 
> What do you think about adding Arrow/`insertArrowTable` functionality here?

What would really help is if you could write some version of the testbed.html file that illustrates exactly what it looks like from the caller's end, in particular all the stuff you do to obtain the arrow data object. If you can provide how you'd like to call it, then I can use that and work on the backend to deliver the appropriate response.

Another thing that would be good is to verify that if you send the arrow data object (presumably that would go in the request body), you can receive it whole on the receiving window's side. IOW, does the arrow data object get transferred properly through a postMessage request.

**Comment by declann** [comment]
> > Another thing I'm just after considering is if the parent can create a blob URL and send to the client.
> 
> What did the actual postmessage look like? Can you load such urls using the DuckDB command line directly? (If not, then that's the issue)

I used the UI and gave it a blob URL that I created in the parent console.

I can fetch that URL in the console, suggesting that Huey can access it.

> > But Arrow is especially efficient at this boundary; duckdb uses it internally, and there are good Javascript libraries to generate Arrow tables on the external side (`apache-arrow` and [flechette](https://github.com/uwdata/flechette)).
> > What do you think about adding Arrow/`insertArrowTable` functionality here?
> 
> What would really help is if you could write some version of the testbed.html file that illustrates exactly what it looks like from the caller's end, in particular all the stuff you do to obtain the arrow data object. If you can provide how you'd like to call it, then I can use that and work on the backend to deliver the appropriate response.
> 
> Another thing that would be good is to verify that if you send the arrow data object (presumably that would go in the request body), you can receive it whole on the receiving window's side. IOW, does the arrow data object get transferred properly through a postMessage request.

OK, I've done some of this before, and will package a html file.

**Comment by declann** [comment]
I'm sending an Arrow IPC array here: https://github.com/declann/huey/blob/dev/src/PostMessageInterface/PostMessageArrowTestbed.html

The iframe receives it and alerts the correct length. But there is an issue now. To use `insertArrowTable` we need to call [tableFromIPC](https://arrow.apache.org/docs/js/functions/Arrow_dom.tableFromIPC.html) first: from a library such as apache-arrow or flechette (though, in a separate application only apache-arrow worked for me).

I can get flechette working by ES import from a URL. I don't think apache-arrow works without a bundler. Neither suit hueys no-dependency model.

This means that `insertArrowTable` might be unworkable (without considering cherry picking some code for inclusion).

duckdb also has [`insertArrowFromIPCStream`](https://duckdb.org/docs/api/wasm/data_ingestion#apache-arrow), which I haven't used before and the API is clearly a little different. If that can work directly on the IPC array without `tableFromIPC`, that would be the way to get the array loaded.

If you want me to look into that I can; I just may not get around to it this week.

**Comment by rpbouman** [comment]
@declann thanks for your sample! 

> But there is an issue now. 

Ok. Then for now let's keep it simple. I just added an example to PostMessageTestbed that illustrates how you can send arbitrary data programmatically. It still works with File objects, but rather than getting the file from an `<input type="file"/>`, I'm just using the `File()` constructor directly: https://github.com/rpbouman/huey/blob/dev/src/PostMessageInterface/PostMessageTestbed.html#L109

The File constructor can be passed data in many different ways (see https://developer.mozilla.org/en-US/docs/Web/API/File/File), but this is just part of the standard API and up to the user.

In the example, I'm sending a csv "file", but there is no reason why it shouldn't also work for JSON (or even binary data in the parquet format)

It may be a little less convenient than being able to send arrow tables directly, but on the upside, this presumes only standard built-ins, and it keeps everything very transparent and simple

**Comment by declann** [comment]
Hi Roland,

Wow, I totally missed the File constructor.

This looks like it does indeed close the issue.

I haven't looked closely, but when I do I'll complete the 'challenge' I
placed here: ***@***.***/embedded-huey-data-load

Perhaps I'll get to try this for a vscode extension, and if Arrow might
point to big efficiencies I'll create a separate issue; but I think this
should be workable!

I also agree this is quite transparent and simple - good work!

Thanks!
Declan

**Comment by rpbouman** [comment]
Ok Declan! 

Well, I'll just close this issue for now. Thank you for filing the request, it took a while but I think the tool is now better thanks to that.

If anything comes up or you feel it needs to be reopened, feel free to do so. 
If there are other requests for improvements and/or alternative ways then please create new issues for those. 

Thank in advance!
