### ISSUE TITLE
feature request: load data from URL

### ISSUE THREAD

**Issue by declann** [rpbouman/huey#144]
I think this would be useful.

There might be at least two approaches to this:

- DuckDB has functionality to point to URLs
- `fetch` the url and process the file similar (I guess) to existing process

edit: I just read #81 ; using this feature this might make it possible to share complete links to huey output (if data url and report state both included in url hash)

**Comment by rpbouman** [comment]
This is now supported.

![image](https://github.com/user-attachments/assets/28d5edab-3899-4007-863e-b5f548a6b412)

**Comment by declann** [comment]
Looks nice but just gave this a go and it doesn't seem to work for me:

![image](https://github.com/user-attachments/assets/2c67f642-0f2c-422f-8be1-87a083bae22f)

I'm trying this url: `https://huggingface.co/datasets/severo/test-parquet/resolve/main/parquet/csv-train-00000-of-00001.parquet?download=true`

One error in the console but it occurs when I load the app, probably related however?

![image](https://github.com/user-attachments/assets/abaffe12-3ccd-4bcc-92b6-377ab987b00b)

Using Firefox but exact same issue on Chrome.

**Comment by rpbouman** [comment]
@declann , thanks for trying! Looking into it.

**Comment by declann** [comment]
Interesting! I wonder where does the huey requirement comes from?

This sample URLs work in duckdb shell, but not in huey:

![image](https://github.com/user-attachments/assets/c0dbeacb-ff12-47f9-a173-def9d0f35b71)

**Comment by rpbouman** [comment]
Hi Declann!

>  I wonder where does the huey requirement comes from?

Yeah it's a good question. It's not really the mime type I care about, it's just that I try to specify the exact reader. And in order to do that I need to know what type of file it is. For local files I would simply check the file extension, which is of course very crude but also not terribly unreasonable and at least easy to explain. 

With url's it becomes a bit trickier and I thought I could spare myself the trouble of parsing the url to discover the extension (if present) by just asking the server what the mime type is.

I know that in duckdb we can just say,SELECT FROM "file", and then duckdb will do it's best to find out what reader to use. But there is no way that I know of afterwards to figure out what reader duckdb ends up using.

The reason for wanting to explicitly specify the reader is that different readers have different parameters and settings, I want the user to be able to control that and where possible benefit from the specific reader's capabilities.

But you make a good point, huey's file detection capabilities (or lack thereof) should not hamper user experience.

I think I can probably work around it, I just need a little bit of time. To be continued, soon.

**Comment by declann** [comment]
Makes sense now, thanks a lot for that explanation Roland!

**Comment by rpbouman** [comment]
Hi @declann, can you give it another go? I think it should be a bit more robust now.
TIA!

**Comment by declann** [comment]
Happy to try it! But sadly nothing noticeable loads for me after I enter the URL. I notice one query posted to console though:

![image](https://github.com/user-attachments/assets/210da5cf-7a02-4399-8e77-144c2615ea1e)

**Comment by rpbouman** [comment]
I just checked the online demo and I'm seeing the same for that! That's really odd. Looking into it - sorry for the inconvenience.

**Comment by declann** [comment]
No worries at all!!

**Comment by rpbouman** [comment]
ok sorry bout that. Try again pls?

**Comment by declann** [comment]
Works and is awesome! Thanks!
