### ISSUE TITLE
Using Huey as application GUI/dashboard?

### ISSUE THREAD

**Issue by javafanboy** [rpbouman/huey#163]
I would have liked to launch Huey from within A Java application to visualize downloaded/processed files but this would require programmatically both register the files as data sources and launch a pre-configured configuration with what columns, filtering, sorting etc. that should be shown.

Is this somehow possible already today or planed as an enhancement?

**Comment by rpbouman** [comment]
Hi Javafanboy, 

yeah I had a few discussions about this with @declan https://github.com/rpbouman/huey/issues/143

As it stands today, you can launch huey and use the hash fragment of the url to pass in a query. 
(To see how that works, just open a url and add some items to the axes, you should see the url change and the hash get updated. look at https://github.com/rpbouman/huey/blob/dev/src/Routing/Routing.js#L4 to see how that's decoded and at https://github.com/rpbouman/huey/blob/dev/src/Routing/Routing.js#L18 to see how it's encoded)
 
The query has a reference to a datasource, and this may be either a file or a url.
If it is a url, it will be loaded automatically (provided the server has the right CORS headers set) 
(https://github.com/rpbouman/huey/issues/144). Huey will register it as a file automatically in this case.

If it is a file, huey will pop up a dialog to invite the user to browse but that is probably not what you would want, as there is now way to control what file the user will pick.

There has been some talk of the possibility to use postMessage (https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to control the huey application by applications that embed huey in a frame (or iframe). I did some tests with that but it would need work to deliver it. 

I have the start of a postmessage module that would handle the huey side of it.

I've been holding off building this because it would require a stable API and I'm currently still adding new basic features, like support for nested data types. However, if you have very concrete plans and you can make concrete specifications out of them, then maybe we can collaborate and give this priority.

**Comment by javafanboy** [comment]
Sadly I dont have any clue about web development and is just looking for a
"minimal effort" analytic solution for a hoby project of mine (may one day
be an open source project) so I do not have much to offer except possibly a
wish list of features 😩

I am more of a backbend developer with a passion for big data)analytics
(and of course Java 😄)... I really like many of the feature of DuckDB and
was happy that somebody had added a GUI and made it usable in the browser
but I may be a bit "in front" of the development of huey right now...

**Comment by rpbouman** [comment]
This is currently supported using the PostMessageInterface. see the example here: https://github.com/rpbouman/huey/blob/dev/src/PostMessageInterface/PostMessageTestbed.html

**Comment by javafanboy** [comment]
Great - will give it a try!

**Comment by rpbouman** [comment]
I forgot to clarifiy: it's in the dev branch. 
The main branch, which is where the online demo comes from will get this in the not too distant future.
