### ISSUE TITLE
Avoiding dependency on jsdelivr.com?

### ISSUE THREAD

**Issue by javafanboy** [rpbouman/huey#168]
According to the doc huey "depends on resources served by jsdelivr.com" - can this be avoided? I have a feeling the security dep of my company will be uneasy with something communicating over Internet (even if it, I assume, only is intended to "read") while visualizing company data due to fear of data exfiltration etc. Would be nice to set up a 100% local installation by once and for all download those resources locally - is this possible?

**Comment by rpbouman** [comment]
Hi!

There is already an issue on this topic, see: https://github.com/rpbouman/huey/issues/138

> Would be nice to set up a 100% local installation by once and for all download those resources locally - is this possible?

It depends on what you mean by "local". DuckDB is distributed as a ES Module, which is added to the page using the javascript import statement. That already precludes loading from the file system directly, it has to come from HTTP. 

However, rather than using JSdeliver, you could set up your own webserver, either inside your company intranet, or even on your local workstation, and host the resources from there. You can find some information on that in the DuckDB WASM documentation here: https://duckdb.org/docs/api/wasm/instantiation#statically-served

Another thing to consider is that the external resources only have to be downloaded once - after that they are cached by the browser, and huey will still work even if you're not connected to the internet.

**Comment by javafanboy** [comment]
Thanks for the detailed and helpful answer.

**Comment by declann** [comment]
Just a comment - I think data exfiltration is a risk even if file is served locally: POST is still possible afaik - though not the case if running/kept in Offline mode.

Specifying a content security policy either through the page head or by embedding it in an iframe sandbox might make this safer - Not a security expert though
