### ISSUE TITLE
Would it be possible for Huey to read an existing DuckDB db file from a known location in localhost?

### ISSUE THREAD

**Issue by ramkumarkb** [rpbouman/huey#201]
Hi Roland,

Thank you for the nice project - Huey !

I have a usecase where Huey would need to read an existing DuckDB db file from a known folder path (in localhost, from where Huey is also running). Kind of "hardcoded DB location" - instead of uploading the actual `.duckdb` file from the UI.

I looked thru the code and this would need some changes in source folder `/src/DataSource` to read DuckDB file from a location ?

Line 15 for `https://github.com/rpbouman/huey/blob/dev/src/DataSource/duckdb/DuckDbConnection.js` - would that be approximately correct?

**Comment by rpbouman** [comment]
Hi @ramkumarkb,

thanks for your interest in huey!
So if I understand correctly, you want a huey instance that is constrained to a single datasource, coming from a duckdb data file from a fixed path?

If you're running huey directly in your browser, without a webserver (url will be like file:///path/to/local/huey/src/index.html), then you won't be able to use local files (including database files) unless the user explicitly chooses them with the file chooser/upload.

If the file you're accessing is served via http then the resources is in principle accessible as long as the server sets the right CORS headers, but you're right that at this point, huey probably won't detect the proper file type unless it has the .duckdb extension. However, in this case, it will be possible to make a slightly modified version of huey that loads your database file on startup. 

> Line 15 for https://github.com/rpbouman/huey/blob/dev/src/DataSource/duckdb/DuckDbConnection.js - would that be approximately correct?

I'm don't think that's where you'd make that modification. That line creates a connection to the duckdb instance. But the duckdb instance is just a running version of the software, not necessarily attached to a database file.

If I had your requirement, I suggest checking out all the code (either clone repo or download all code) and then make a modification to the initscript at the bottom of index.html. There are lines like this there:
```
        await db.instantiate(bundle.mainModule, bundle.pthreadWorker);
        const connection = await db.connect();
```
When that completes, you could try to call src/DataSource/duckdb/DuckDBDataSource#createFromUrl (line 248), assuming your duckdb file is accessible via a http url to create a datasource for your database file.

However, some modifications are probably necessary to allow you to tell huey that you're trying to load a database file rather than just some data file.

I hope this helps!

**Comment by ramkumarkb** [comment]
Hi @rpbouman ,

Thank you for the reply! My usecase is as follows - 

- Huey is being served from a WebServer that hosts Huey
- As Huey starts-up, Huey connects to a DuckDB database file also located in the same server
- That is, the user (from the browser) does not provide a Datasource but it is kind of "harcoded" to the DuckDB located in the same server as Huey
- I think this should be possible - there is no browser limitation here (I think). It is like Huey is only serving the DuckDB database.

To do this, which files would I need to change?

Thanks again for your guidance!

best,

**Comment by rpbouman** [comment]
Hi @ramkumarkb, 

I have seen your reply but have not yet found the time to properly answer it. I will get back to you on this later this week, probably wednesday

**Comment by rpbouman** [comment]
Hi @ramkumarkb, I made some changes that would support your request.
To implement it yourself, make sure you get the latest dev branch, and then apply your changes as needed on top.

I prepared a branch that illustrates the customization that you might make:

set-upstream origin issue-201-load-duckdb-from-url-at-startup

The customization is in the bottom script element in index.html, after the initApplication() call.
This is it:

```
        // custom script to load a duckdb database on startup.
        var datasource = await DuckDbDataSource.createFromUrl(
          window.hueyDb.duckdb, 
          window.hueyDb.instance,
          'http://localhost/files/tripdata.duckdb'
        );
        await datasource.validateAccess();
        datasourcesUi.addDatasource(datasource);
```

Obviously, you would modify the third argument to DuckDbDataSource.createFromUrl to match the url of your duckdb file.

I hope this helps! Let me know.

Cheers,
Roland.

**Comment by rpbouman** [comment]
@ramkumarkb, did you get a chance to check this out? Please let me know and if this is what you meant, kindly close the issue.

**Comment by rpbouman** [comment]
Ok @ramkumarkb I think I'm going to close this now. Please re-open if you think it's not fixed.

**Comment by rpbouman** [comment]
That's totally ok @ramkumarkb , no worries! 

Just let me know when you get round to it.
